//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AviaSite
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ticket
    {
        public int TicketId { get; set; }
        [Display(Name ="Flight")]
        public int FlightId { get; set; }
        [Display(Name ="Seat")]
        public string SeatNumber { get; set; }
    
        public virtual Flight Flight { get; set; }
    }
}
